version: '3'
networks: 
  laravel:
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel
    ports:
      - "8080:80"
    volumes:
      - ./backend/laravel:/var/www/laravel
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgresql
    networks:
      - laravel
  php:
    image: kurt6783/iron_man
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./backend/laravel:/var/www/laravel
    networks:
      - laravel
  postgresql:
    image: mdillon/postgis:10
    container_name: postgresql
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./backend/postgresql:/var/lib/postgresql/data
    networks: 
      - laravel